# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on releases
on:
  release:
    types: [created]  

env:
  SKETCH_NAME: space_invaders
  PROCESSING_VERSION: 3.5.4

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platforms: [linux, windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: sylvanld/build-processing-action@v1
        with:
          sketch: ${{env.SKETCH_NAME}}
          processing_version: ${{env.PROCESSING_VERSION}}
          target_platform: ${{matrix.platforms}}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/${{matrix.platforms}}.zip
          asset_name: ${{env.SKETCH_NAME}}-${{matrix.platforms}}.zip
          asset_content_type: application/zip
